baseURL = "https://tchungblog.netlify.app"
disableLanguages = []
disqusShortname = ""
googleAnalytics = "UA-123-45"
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "Timo's Blog"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
name = "About"
url = "https://timochung.netlify.app"
weight = 1
[[menu.main]]
name = "About"
url = "https://timochung.netlify.app"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "This is meta description"
[params.banner]
heading = "The New UMoMA Opens its Doors"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "The premier destination for modern art in Northern Sweden. Open from 10 AM to 6 PM every day during the summer months."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = true
title = "Contact us for more information."
[params.footer]
address = ""
content = "I'm Timothy, a student at ECIM. My interests lie in the sciency and computery stuff, plus a lot more. See more [here](https://timochung.netlify.app)."
copyright = "Copyright &copy; 2020"
hours = ""
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
